# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-08-13 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20200813_0649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortnerUrl',
            new_name='Url',
        ),
    ]
