# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-08-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_url_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=220, unique=True, validators=[shortner.validators.validate_url]),
        ),
    ]
